/*
 * Unity Catalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.unitycatalog.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.unitycatalog.client.model.CommitInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetCommits200Response
 */
@JsonPropertyOrder({
  GetCommits200Response.JSON_PROPERTY_COMMITS,
  GetCommits200Response.JSON_PROPERTY_LATEST_TABLE_VERSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class GetCommits200Response {
  public static final String JSON_PROPERTY_COMMITS = "commits";
  private List<CommitInfo> commits = new ArrayList<>();

  public static final String JSON_PROPERTY_LATEST_TABLE_VERSION = "latest_table_version";
  private Long latestTableVersion;

  public GetCommits200Response() { 
  }

  public GetCommits200Response commits(List<CommitInfo> commits) {
    this.commits = commits;
    return this;
  }

  public GetCommits200Response addCommitsItem(CommitInfo commitsItem) {
    if (this.commits == null) {
      this.commits = new ArrayList<>();
    }
    this.commits.add(commitsItem);
    return this;
  }

   /**
   * Get commits
   * @return commits
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CommitInfo> getCommits() {
    return commits;
  }


  @JsonProperty(JSON_PROPERTY_COMMITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommits(List<CommitInfo> commits) {
    this.commits = commits;
  }


  public GetCommits200Response latestTableVersion(Long latestTableVersion) {
    this.latestTableVersion = latestTableVersion;
    return this;
  }

   /**
   * The latest tracked version.
   * @return latestTableVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_TABLE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLatestTableVersion() {
    return latestTableVersion;
  }


  @JsonProperty(JSON_PROPERTY_LATEST_TABLE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestTableVersion(Long latestTableVersion) {
    this.latestTableVersion = latestTableVersion;
  }


  /**
   * Return true if this getCommits_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCommits200Response getCommits200Response = (GetCommits200Response) o;
    return Objects.equals(this.commits, getCommits200Response.commits) &&
        Objects.equals(this.latestTableVersion, getCommits200Response.latestTableVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commits, latestTableVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCommits200Response {\n");
    sb.append("    commits: ").append(toIndentedString(commits)).append("\n");
    sb.append("    latestTableVersion: ").append(toIndentedString(latestTableVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `commits` to the URL query string
    if (getCommits() != null) {
      for (int i = 0; i < getCommits().size(); i++) {
        if (getCommits().get(i) != null) {
          joiner.add(getCommits().get(i).toUrlQueryString(String.format("%scommits%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `latest_table_version` to the URL query string
    if (getLatestTableVersion() != null) {
      joiner.add(String.format("%slatest_table_version%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLatestTableVersion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

